In [2]:
import pandas as pd

In [5]:
df = pd.read_parquet('C:\\Users\\jeanduckens.sannon\\OneDrive - Cdiscount\\Documents\\LightGBM_Forecasting\\lightgbm_forecast\\data\\raw\\df_complet_filtre.parquet')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3565935 entries, 0 to 3565934
Data columns (total 10 columns):
 #   Column        Dtype
---  ------        -----
 0   date          datetime64[ns]
 1   search_id     object
 2   tail          float64
 3   cat1          object
 4   cat2          object
 5   cat3          object
 6   vues_lr       int64
 7   clics_lr      int64
 8   va_lr         float64
 9   commandes_lr  int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(4)
memory usage: 272.1+ MB

In [20]:
df['date'].min(), df['date'].max()

(Timestamp('2024-10-06 00:00:00'), Timestamp('2025-10-15 00:00:00'))

In [41]:
date_ref_start_test = pd.Timestamp('2025-07-01')  # Pour prédire 3 nov
date_ref_end_test = pd.Timestamp('2025-08-06')    # Pour prédire 12 nov

In [42]:
df_date_test = pd.DataFrame({'date': pd.date_range(start=date_ref_start_test, end=date_ref_end_test)})

In [43]:
df_test = df.merge(df_date_test, on='date', how='inner')

In [44]:
df_test

,date,search_id,tail,cat1,cat2,cat3,vues_lr,clics_lr,va_lr,commandes_lr
0,2025-07-01,chambreaairvelo,48.3722,SPORT,MOBILITE,ACCESSOIRES CYCLES,5,3,0.00,0
1,2025-07-01,reveil,25.3549,IMAGE ET SON,SON,SON NOMADE,33,24,82.86,4
2,2025-07-01,sonicps5,49.7510,JEUX VIDEO,JEUX VIDEO,JEUX POUR CONSOLES SONY,1,1,26.87,1
3,2025-07-01,coquea13,49.5597,TELEPHONIE,ACCESSOIRES - CHARGEURS - OREILLETTES - MÉMOIRE,COQUE TELEPHONE - BUMPER TELEPHONE,4,3,19.57,2
4,2025-07-01,stitchpeluche,39.3632,JEUX - JOUETS,UNIVERS MINIATURE - POUPEE ET PELUCHE,POUPEE - PELUCHE,4,2,0.00,0
...,...,...,...,...,...,...,...,...,...,...
365652,2025-08-06,13mini,49.1465,TELEPHONIE,MOBILE - SMARTPHONE,SMARTPHONE,15,12,259.86,1
365653,2025-08-06,telephoneiphone11,42.1298,TELEPHONIE,MOBILE - SMARTPHONE,SMARTPHONE,4,1,0.00,0
365654,2025-08-06,meubleindustrielboismetal,49.7610,MEUBLES,JOUR,BUFFET - BAHUT - ENFILADE,1,0,0.00,0
365655,2025-08-06,suspensionluminairerotin,46.2911,PMA,LUMINAIRES,SUSPENSION - PLAFONNIER,10,7,18.90,1
365656,2025-08-06,tarot,48.7397,JEUX - JOUETS,JEUX DE SOCIETE - MULTIMEDIA,JEUX DE SOCIETE,5,3,0.00,0

In [3]:
df_pred = pd.read_csv(r'C:\Users\jeanduckens.sannon\OneDrive - Cdiscount\Documents\LightGBM_Forecasting\lightgbm_forecast\data\predictions\predictions_hiver_2026.csv')

In [4]:
df_pred['date'].min(), df_pred['date'].max()

('2024-12-11', '2025-12-16')

In [8]:
df_pred.head(100)

          date                 search_id  vues_predites_log  vues_predites
0   2024-12-11                         1           2.321233       9.188231
1   2024-12-11     plaqueinduction5foyer           2.376741       9.769751
2   2024-12-11  plaqueinductionaspirante           2.400569      10.029453
3   2024-12-11    plaqueinductionblanche           2.384087       9.849152
4   2024-12-11      plaqueinductionbosch           2.699341      13.869925
..         ...                       ...                ...            ...
95  2024-12-11           playmobilgarcon           1.278401       2.590892
96  2024-12-11             plaquecheveux           2.333531       9.314297
97  2024-12-11            playmobilfille           1.944196       5.988010
98  2024-12-11        playmobildinosaure           2.002317       6.406196
99  2024-12-11                   plateau           2.999940      19.084330

[100 rows x 4 columns]

In [9]:
df_pred['date_28_days_ahead'] = pd.to_datetime(df_pred['date']) + pd.Timedelta(days=28)

In [11]:
date_ref_start = pd.Timestamp('2025-12-10')  # Pour prédire 7 JAN
date_ref_end = pd.Timestamp('2025-12-16')    # Pour prédire 13 JAN

In [12]:
df_pred_date = pd.DataFrame({'date' : pd.date_range(start=date_ref_start, end=date_ref_end)})

In [13]:
df_pred_date['date'].nunique()

7

In [14]:
# ensure df_pred['date'] is datetime so it matches df_pred_date['date']
df_pred['date'] = pd.to_datetime(df_pred['date'])
df_final_pred = df_pred_date.merge(df_pred, on='date', how='inner')

In [15]:
df_pred

,date,search_id,vues_predites_log,vues_predites,date_28_days_ahead
0,2024-12-11,1,2.321233,9.188231,2025-01-08
1,2024-12-11,plaqueinduction5foyer,2.376741,9.769751,2025-01-08
2,2024-12-11,plaqueinductionaspirante,2.400569,10.029453,2025-01-08
3,2024-12-11,plaqueinductionblanche,2.384087,9.849152,2025-01-08
4,2024-12-11,plaqueinductionbosch,2.699341,13.869925,2025-01-08
...,...,...,...,...,...
6508529,2025-12-16,antipucechien,2.306295,9.037171,2026-01-13
6508530,2025-12-16,samsunga33,2.838959,16.097964,2026-01-13
6508531,2025-12-16,citysports,2.388419,9.896258,2026-01-13
6508532,2025-12-16,batterieveloelectrique,2.333806,9.317130,2026-01-13
6508533,2025-12-16,zinc,2.042273,6.708106,2026-01-13

In [16]:
df_final_pred['date_28_days_ahead'].min(), df_final_pred['date_28_days_ahead'].max()

(Timestamp('2026-01-07 00:00:00'), Timestamp('2026-01-13 00:00:00'))

In [21]:
df_final_pred.head(100)

,date,search_id,vues_predites_log,vues_predites,date_28_days_ahead
0,2025-12-10,poeleethanol,2.455926,10.657222,2026-01-07
1,2025-12-10,drapplat1personne,2.563229,11.977655,2026-01-07
2,2025-12-10,remington,2.833824,16.010381,2026-01-07
3,2025-12-10,protectionipad,2.276286,8.740440,2026-01-07
4,2025-12-10,filetdecamouflage,2.596349,12.414678,2026-01-07
...,...,...,...,...,...
95,2025-12-10,suspensionrotin,2.778980,15.102592,2026-01-07
96,2025-12-10,maryse,2.322889,9.205111,2026-01-07
97,2025-12-10,buffet140cm,2.443107,10.508740,2026-01-07
98,2025-12-10,galaxys24ultra,4.253963,69.383778,2026-01-07
99,2025-12-10,johnnyhallyday,2.661128,13.312420,2026-01-07

In [18]:
df_final_pred['date_28_days_ahead'].nunique()

7

In [22]:
df_final_pred.groupby('search_id').agg({'vues_predites': 'sum'}).reset_index()

        search_id  vues_predites
0               1      80.193754
1              10      63.932020
2      100logique      34.317078
3        10prcent       6.944037
4              11      92.786304
...           ...            ...
18313      zfold6     524.008952
18314      zfold7      99.234786
18315       zibro      67.245917
18316      zigbee      77.265079
18317        zinc      43.530705

[18318 rows x 2 columns]

In [23]:
df_final_pred_grouped = df_final_pred.groupby('search_id').agg({'vues_predites': 'sum'}).reset_index()

In [24]:
df_final_pred_grouped.sort_values(by='vues_predites', ascending=False).head(50)

                    search_id  vues_predites
7695                 iphone14   21862.338530
7756                 iphone15   21603.101881
7814                 iphone16   20094.381419
7561                   iphone   19814.894796
13404                     ps5   18249.374254
7628                 iphone13   18099.994844
16762              television   16598.113281
2619                   canape   15686.738649
11661      ordinateurportable   14630.434467
10633                meubletv   12279.643780
8580                lavelinge   12276.961987
17263    trotinetteelectrique   12195.724827
4040                coiffeuse   10545.938306
8646            lavevaisselle   10508.746981
3313       chaisesalleamanger    9908.423979
16680       telephoneportable    9853.664768
10172          matelas140x190    9761.996053
2665        canapeconvertible    9322.242666
14485                 samsung    9214.709702
16224                tablette    9097.055620
9021               lit140x190    8798.226485
7718              iphone14pro    8724.678023
15827            tableamanger    8460.178836
6480                    frigo    8386.235696
7586                 iphone12    8233.641489
7862                 iphone17    8230.389041
815                aspirateur    7609.708644
14941              sechelinge    7505.647696
10760               microonde    7319.581151
8752                     lego    7121.096378
5415                 dressing    7037.749193
9052               lit160x200    6879.418621
10194          matelas160x200    6671.142420
2147                   bureau    6583.556672
6498         frigocongelateur    6580.317203
14752              samsungs24    6565.939918
701                   armoire    6546.144123
10384       meubleachaussures    6515.459814
877          aspirateurlaveur    6497.041251
290                  airfryer    6396.857887
2694             canapedangle    6394.365563
4162                  commode    6331.040625
14767              samsungs25    6249.242149
6430          fourencastrable    6134.328446
839    aspirateurbalaisansfil    6017.115513
16531              tapissalon    5892.586430
7505                     ipad    5709.839668
9011                      lit    5533.144783
12116                 pcgamer    5501.070197
7838           iphone16promax    5276.549036

In [25]:
df_final_pred_grouped['vues_predites'] = df_final_pred_grouped['vues_predites'].astype(int)

In [26]:
df_final_pred_grouped.sort_values(by='vues_predites', ascending=False)

                       search_id  vues_predites
7695                    iphone14          21862
7756                    iphone15          21603
7814                    iphone16          20094
7561                      iphone          19814
13404                        ps5          18249
...                          ...            ...
12607            plancheboisbrut              3
2795   canapes3placesconvertible              3
10745                  michou100              2
261          agendasemainier2025              2
6479                  frigidaire              1

[18318 rows x 2 columns]

In [27]:
df_final_pred_grouped.to_csv('final_predictions_total_de_01_07_au_01_13_2026.csv', index=False)

In [28]:
df_final_grouped_topK = df_final_pred_grouped.sort_values(by='vues_predites', ascending=False).head(1500)

In [29]:
df_final_grouped_topK.to_csv('final_predictions_HIVER_de_01_07_au_01_13_2026.csv', index=False)

In [30]:
df_final_grouped_topK

                search_id  vues_predites
7695             iphone14          21862
7756             iphone15          21603
7814             iphone16          20094
7561               iphone          19814
13404                 ps5          18249
...                   ...            ...
109        abonnementiptv            355
13428                 psg            355
10978              mobile            355
11479  nintendoswitchlite            355
8452         lamederasoir            355

[1500 rows x 2 columns]

In [23]:
df_test = df_test.merge(df_pred[['date', 'search_id', 'vues_predites']], on=['date', 'search_id'], how='inner')

NameError: name 'df_test' is not defined

In [48]:
df_test['date'].min(), df_test['date'].max()

(Timestamp('2025-07-01 00:00:00'), Timestamp('2025-08-06 00:00:00'))

In [50]:
df_test_agg = df_test.groupby('search_id').agg({'vues_lr': 'sum', 'vues_predites': 'sum'}).reset_index()

In [51]:
df_test_agg

          search_id  vues_lr  vues_predites
0                 1      344     185.821712
1                10      199     112.772268
2        100logique        2      38.324781
3                11       97      69.551549
4             11pro      110      80.763273
...             ...      ...            ...
22967         zibro        3      24.612120
22968        zigbee       38      37.356663
22969          zinc      208     144.865306
22970  zodiacbateau      138      71.310975
22971           zte       18      34.127853

[22972 rows x 3 columns]

In [52]:
top_k_search_id_reel = df_test_agg.sort_values(by='vues_lr', ascending=False).head(1_000)['search_id'].tolist()
top_k_search_id_pred = df_test_agg.sort_values(by='vues_predites', ascending=False).head(1_000)['search_id'].tolist()

In [53]:
df_test_agg["is_top_k_reel"] = df_test_agg["search_id"].apply(lambda x: x in top_k_search_id_reel)
df_test_agg["is_top_k_pred"] = df_test_agg["search_id"].apply(lambda x: x in top_k_search_id_pred)

In [54]:
from sklearn.metrics import recall_score
recall = recall_score(df_test_agg["is_top_k_reel"], df_test_agg["is_top_k_pred"])
print(f"Recall: {recall:.2f}")

Recall: 0.89

In [14]:
df_bf = pd.read_parquet('C:\\Users\\jeanduckens.sannon\\OneDrive - Cdiscount\\Documents\\LightGBM_Forecasting\\lightgbm_forecast\\data\\raw\\data_fresh_bf_2025.parquet')

In [15]:
df_bf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7899418 entries, 0 to 7899417
Data columns (total 10 columns):
 #   Column        Dtype
---  ------        -----
 0   date          datetime64[ns]
 1   search_id     object
 2   tail          float64
 3   cat1          object
 4   cat2          object
 5   cat3          object
 6   vues_lr       int64
 7   clics_lr      int64
 8   va_lr         float64
 9   commandes_lr  int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(4)
memory usage: 602.7+ MB

In [15]:
df_pred['date_28_days_ahead'] = pd.to_datetime(df_pred['date']) + pd.Timedelta(days=28)

In [16]:
df_pred.head()

,date,search_id,vues_predites_log,vues_predites,date_28_days_ahead
0,2024-10-01,1,2.552467,11.838741,2024-10-29
1,2024-10-01,debroussailleusestihl,2.082572,7.025085,2024-10-29
2,2024-10-01,debroussailleusethermique,4.315462,73.848213,2024-10-29
3,2024-10-01,trotinetteadulte,2.820932,15.792488,2024-10-29
4,2024-10-01,debroussailleusethermique4en1,2.276614,8.743633,2024-10-29

In [7]:
date_ref_start_bf = pd.Timestamp('2025-11-21')  # Pour prédire 21 NOV   
date_ref_end_bf = pd.Timestamp('2025-12-02')    # Pour prédire 02 DEC

In [8]:
date_ref_start_bf - pd.Timedelta(days=28), date_ref_end_bf - pd.Timedelta(days=28)

(Timestamp('2025-10-24 00:00:00'), Timestamp('2025-11-04 00:00:00'))

In [9]:
date_ref_start_bf_2025 = pd.Timestamp('2025-10-24')  # Pour prédire 21 NOV
date_ref_end_bf_2025 = pd.Timestamp('2025-11-04')    # Pour prédire 02 DEC

In [10]:
df_pred_date_2025 = pd.DataFrame({'date' : pd.date_range(start=date_ref_start_bf_2025, end=date_ref_end_bf_2025)})

In [11]:
df_pred_date_2025['date'].nunique()

12

In [ ]:
df_pred['date'] = pd.to_datetime(df_pred['date'])
df_final_pred = df_pred_date.merge(df_pred, on='date', how='inner')